import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://rahulshettyacademy.com/client/auth/login');
  await page.getByPlaceholder('email@example.com').click();
  await page.getByPlaceholder('email@example.com').click();
  await page.getByPlaceholder('email@example.com').fill('pandeyanish2001@gmail.com');
  await page.getByPlaceholder('enter your passsword').click();
  await page.getByPlaceholder('enter your passsword').fill('Pandey@123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('div:nth-child(3) > .card > .card-body > button:nth-child(4)').click();
  await page.getByRole('button', { name: '   Cart' }).click();
  await page.getByRole('button', { name: 'Checkout❯' }).click();
  await page.locator('input[type="text"]').first().click();
  await page.locator('input[type="text"]').first().press('ArrowRight');
  await page.locator('input[type="text"]').first().press('ArrowRight');
  await page.locator('input[type="text"]').first().press('ArrowRight');
  await page.locator('input[type="text"]').first().press('ArrowRight');
  await page.locator('input[type="text"]').first().press('ArrowRight');
  await page.locator('input[type="text"]').first().press('ArrowRight');
  await page.locator('input[type="text"]').first().press('ArrowRight');
  await page.locator('input[type="text"]').first().press('ArrowRight');
  await page.locator('input[type="text"]').first().fill('763567438765');
  await page.getByRole('combobox').first().selectOption('06');
  await page.getByRole('combobox').nth(1).selectOption('08');
  await page.locator('input[type="text"]').nth(1).click();
  await page.locator('input[type="text"]').nth(1).fill('555');
  await page.locator('input[type="text"]').nth(2).click();
  await page.locator('input[type="text"]').nth(2).fill('anish kumar');
  await page.getByPlaceholder('Select Country').click();
  await page.getByPlaceholder('Select Country').fill('ind');
  await page.getByRole('button', { name: ' India' }).click();
  await page.getByText('Place Order').click();
  await page.getByText('Orders History Page').click();
  await page.getByRole('rowheader', { name: '67a1ad7be2b5443b1f466a18' }).click();
  await page.getByRole('button', { name: 'View' }).first().click();
  await page.getByText('View Orders').click();
  await page.getByRole('button', { name: 'Go Back to Shop' }).click();
});